# Generated by Django 3.0.2 on 2020-01-30 04:47

from django.db import models, migrations
from datetime import datetime


def load_supplier_types(apps, schema_editor):
    SupplierType = apps.get_model("products", "SupplierType")
    SupplierType(id=0, created=datetime.utcnow(), type="tour_operator").save()
    SupplierType(id=1, created=datetime.utcnow(), type="flight_company").save()
    SupplierType(id=2, created=datetime.utcnow(), type="insurance_company").save()
    SupplierType(id=3, created=datetime.utcnow(), type="bed_bank").save()


def delete_supplier_types(apps, schema_editor):
    SupplierType = apps.get_model("products", "SupplierType")
    SupplierType.objects.all().delete()


def load_product_types(apps, schema_editor):
    ProductType = apps.get_model("products", "ProductType")
    ProductType(id=0, created=datetime.utcnow(), type="bundle").save()


def delete_product_types(apps, schema_editor):
    ProductType = apps.get_model("products", "ProductType")
    ProductType.objects.all().delete()


def load_itinerary_step_types(apps, schema_editor):
    ItineraryStepType = apps.get_model("products", "ItineraryStepType")
    ItineraryStepType(id=0, created=datetime.utcnow(), type="travel").save()
    ItineraryStepType(id=1, created=datetime.utcnow(), type="accommodation").save()


def delete_itinerary_step_types(apps, schema_editor):
    ItineraryStepType = apps.get_model("products", "ItineraryStepType")
    ItineraryStepType.objects.all().delete()


def load_occupancies(apps, schema_editor):
    Occupancy = apps.get_model("products", "Occupancy")
    Occupancy(id=0, tot_adults=1, occupancy_code="1A").save()
    Occupancy(id=1, tot_adults=2, occupancy_code="2A").save()
    Occupancy(id=2, tot_adults=3, occupancy_code="3A").save()
    Occupancy(id=3, tot_adults=4, occupancy_code="4A").save()
    Occupancy(id=4, tot_adults=5, occupancy_code="5A").save()
    Occupancy(id=5, tot_adults=6, occupancy_code="6A").save()


def delete_occupancies(apps, schema_editor):
    Occupancy = apps.get_model("products", "Occupancy")
    Occupancy.objects.all().delete()


def load_ancillary_service_types(apps, schema_editor):
    AncillaryServiceType = apps.get_model("products", "AncillaryServiceType")
    AncillaryServiceType(id=0, created=datetime.utcnow(), name='insurance').save()


def delete_ancillary_service_types(apps, schema_editor):
    AncillaryServiceType = apps.get_model("products", "AncillaryServiceType")
    AncillaryServiceType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_supplier_types, delete_supplier_types),
        migrations.RunPython(load_ancillary_service_types, delete_ancillary_service_types),
        migrations.RunPython(load_itinerary_step_types, delete_itinerary_step_types),
        migrations.RunPython(load_occupancies, delete_occupancies),
        migrations.RunPython(load_product_types, delete_product_types),
    ]
