# Generated by Django 3.0.2 on 2020-01-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200130_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='productavailability',
            name='occupancy_code',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
