# Generated by Django 3.0.2 on 2020-01-30 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productavailability_occupancy_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancillaryservice',
            name='priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='quantity_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
