# Generated by Django 3.0.2 on 2020-02-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200203_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='productavailability',
            name='availability_key',
            field=models.CharField(db_index=True, default='', max_length=600, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productallotment',
            name='ancillary_services',
            field=models.ManyToManyField(blank=True, to='products.AncillaryService'),
        ),
        migrations.AlterField(
            model_name='productallotment',
            name='departure_options',
            field=models.ManyToManyField(blank=True, to='products.DepartureOption'),
        ),
    ]
