# Generated by Django 3.0.3 on 2020-02-17 13:27

from django.db import migrations
import django_enumfield.db.fields
import server.apps.products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_auto_20200212_0600"),
    ]

    operations = [
        migrations.AddField(
            model_name="ancillaryservice",
            name="selection_type",
            field=django_enumfield.db.fields.EnumField(
                db_index=True,
                default=1,
                enum=server.apps.products.models.ServiceSelectionType,
            ),
        ),
    ]
