# Generated by Django 3.0.3 on 2020-02-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_ancillaryservice_selection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='departureoption',
            name='display_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='departure_option_display_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ancillaryservice',
            name='valid_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ancillaryservice',
            name='valid_to',
            field=models.DateField(null=True),
        ),
    ]
