# Generated by Django 3.0.4 on 2020-03-11 10:13

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import django_extensions.db.fields
import server.apps.products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200226_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='product',
        ),
        migrations.RemoveField(
            model_name='itinerarystepoption',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('version_id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=server.apps.products.models.ProductStatus)),
                ('reservation_date_from', models.DateField(null=True)),
                ('reservation_date_to', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='product_version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.ProductVersion'),
            preserve_default=False,
        ),
    ]
