# Generated by Django 3.0.4 on 2020-03-11 15:54

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200311_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarystep',
            options={},
        ),
        migrations.AddField(
            model_name='itinerarystep',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerarystepoption',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerarystep',
            name='assignation_precedence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itinerarystep',
            name='day_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itinerarystep',
            name='day_to',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='itinerarystepoption',
            name='data',
            field=django_extensions.db.fields.json.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='reservation_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='reservation_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='itinerarystep',
            unique_together={('itinerary', 'order')},
        ),
    ]
