# Generated by Django 3.0.4 on 2020-03-11 17:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200311_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarystepoption',
            options={},
        ),
        migrations.AlterField(
            model_name='itinerarystepoption',
            name='data',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='itinerarystepoption',
            unique_together={('name', 'step')},
        ),
        migrations.CreateModel(
            name='ItinerarySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('departure_day_offset', models.IntegerField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('data', django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Itinerary')),
            ],
            options={
                'unique_together': {('itinerary', 'departure_day_offset')},
            },
        ),
    ]
