# Generated by Django 3.0.4 on 2020-03-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200311_1859'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itineraryschedule',
            unique_together={('itinerary', 'departure_day_offset', 'valid_from')},
        ),
    ]
