# Generated by Django 3.0.4 on 2020-03-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200311_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancillaryservice',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ancillaryservice',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
