# Generated by Django 3.0.4 on 2020-03-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200311_2108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itineraryschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itineraryschedule',
            name='itinerary',
        ),
        migrations.AlterUniqueTogether(
            name='itinerarystep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itinerarystep',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='itinerarystep',
            name='step_type',
        ),
        migrations.AlterUniqueTogether(
            name='itinerarystepoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='itinerarystepoption',
            name='step',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='ItinerarySchedule',
        ),
        migrations.DeleteModel(
            name='ItineraryStep',
        ),
        migrations.DeleteModel(
            name='ItineraryStepOption',
        ),
        migrations.DeleteModel(
            name='ItineraryStepType',
        ),
    ]
