# Generated by Django 3.0.4 on 2020-03-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200312_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVersion',
        ),
    ]
