# Generated by Django 3.0.4 on 2020-03-30 09:48

from django.db import migrations


def adult_validator():
    return {
        "min_age": 18,
        "max_age": None
    }


def adult_validators(tot_adults):
    return [adult_validator() for _ in range(0, tot_adults)]


def u30_validator():
    return {
        "min_age": 18,
        "max_age": 29
    }


def u30_validators(tot_adults):
    return [u30_validator() for _ in range(0, tot_adults)]


def add_under_occupancies(apps, schema_editor):
    Occupancy = apps.get_model("products", "Occupancy")
    Occupancy(id=6, tot_adults=1, occupancy_code="1U30", adult_validators=u30_validators(1)).save()
    Occupancy(id=7, tot_adults=2, occupancy_code="2U30", adult_validators=u30_validators(2)).save()
    Occupancy(id=8, tot_adults=3, occupancy_code="3U30", adult_validators=u30_validators(3)).save()
    Occupancy(id=9, tot_adults=4, occupancy_code="4U30", adult_validators=u30_validators(4)).save()
    Occupancy(id=10, tot_adults=5, occupancy_code="5U30", adult_validators=u30_validators(5)).save()
    Occupancy(id=11, tot_adults=6, occupancy_code="6U30", adult_validators=u30_validators(6)).save()


def delete_under_occupancies(apps, schema_editor):
    Occupancy = apps.get_model("products", "Occupancy")
    Occupancy.objects.filter(pk__in=[6, 7, 8, 9, 10, 11]).delete()


def set_adult_validators(apps, schema_editor):
    Occupancy = apps.get_model("products", "Occupancy")
    Occupancy.objects.filter(occupancy_code="1A").update(adult_validators=adult_validators(1))
    Occupancy.objects.filter(occupancy_code="2A").update(adult_validators=adult_validators(2))
    Occupancy.objects.filter(occupancy_code="3A").update(adult_validators=adult_validators(3))
    Occupancy.objects.filter(occupancy_code="4A").update(adult_validators=adult_validators(4))
    Occupancy.objects.filter(occupancy_code="5A").update(adult_validators=adult_validators(5))
    Occupancy.objects.filter(occupancy_code="6A").update(adult_validators=adult_validators(6))


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20200330_0947'),
    ]

    operations = [
        migrations.RunPython(add_under_occupancies, delete_under_occupancies),
        migrations.RunPython(set_adult_validators)
    ]
