# Generated by Django 3.0.4 on 2020-03-30 10:36

from django.db import migrations
import social_django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200330_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='productavailability',
            name='adult_validators',
            field=social_django.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
