# Generated by Django 3.0.4 on 2020-03-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productavailability_adult_validators'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgeValidator',
        ),
    ]
