# Generated by Django 3.0.5 on 2020-04-11 16:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import social_django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_delete_agevalidator'),
    ]

    operations = [
        migrations.AddField(
            model_name='productavailability',
            name='destination_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='destinations_data',
            field=social_django.fields.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('searchable', models.BooleanField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Destination')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='products.Destination'),
        ),
    ]
