# Generated by Django 3.0.5 on 2020-04-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20200411_1919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='ProductDestination',
        ),
    ]
