# Generated by Django 2.2.3 on 2019-07-30 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StageDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('e_z', models.IntegerField(help_text='E-Z Column D')),
                ('gar_last_season_consumptive', models.IntegerField(help_text='Gar Column E')),
                ('pax_last_season_consumptive', models.IntegerField(help_text='Pax Column F')),
                ('neos_last_season_consumptive', models.IntegerField(help_text='Neos Column G')),
                ('perc_e_z', models.FloatField(help_text='% E-Z Column H')),
                ('gar_last_season_on_date', models.IntegerField(help_text='Gar Column I')),
                ('pax_last_season_on_date', models.IntegerField(help_text='Pax Column J')),
                ('neos_last_season_on_date', models.IntegerField(help_text='Neos Column K')),
                ('perc_occ', models.FloatField(help_text='% occ Column L')),
                ('gar_current_season', models.IntegerField(help_text='Gar Column M')),
                ('pax_current_season', models.IntegerField(help_text='Pax Column N')),
                ('perc_occ_current_season', models.FloatField(help_text='% occ Column O')),
                ('neos_current_season', models.IntegerField(help_text='Neos Column P')),
                ('delta_gar', models.IntegerField(help_text=' Delta Gar Column Q')),
                ('delta_pax', models.IntegerField(help_text='Delta Pax Column Q')),
                ('gar_forecast', models.IntegerField(help_text='Gar Column R', null=True)),
                ('pax_forecast', models.IntegerField(help_text='Pax Column R', null=True)),
                ('neos_forecast', models.IntegerField(help_text='Neos Column R', null=True)),
                ('perc_occ_forecast', models.FloatField(help_text='% occ Column R', null=True)),
                ('last_season_week_four_of_last_four', models.IntegerField(help_text='15/7 column Column S')),
                ('last_season_week_three_of_last_four', models.IntegerField(help_text='8/7 column Column S')),
                ('last_season_week_two_of_last_four', models.IntegerField(help_text='1/7 column Column S')),
                ('last_season_week_one_of_last_four', models.IntegerField(help_text='24/6 column Column S')),
                ('current_season_week_four_of_last_four', models.IntegerField(help_text='14/7 column Column T')),
                ('current_season_week_three_of_last_four', models.IntegerField(help_text='7/7 column Column T')),
                ('current_season_week_two_of_last_four', models.IntegerField(help_text='30/06 column Column T')),
                ('current_season_week_one_of_last_four', models.IntegerField(help_text='23/6 column Column T')),
                ('last_season_week_four_of_last_four_neos', models.IntegerField(help_text='15/7 column Column U')),
                ('last_season_week_three_of_last_four_neos', models.IntegerField(help_text='8/7 column Column U')),
                ('last_season_week_two_of_last_four_neos', models.IntegerField(help_text='1/7 column Column U')),
                ('last_season_week_one_of_last_four_neos', models.IntegerField(help_text='24/6 column Column U')),
                ('current_season_week_four_of_last_four_neos', models.IntegerField(help_text='14/7 column Column V')),
                ('current_season_week_three_of_last_four_neos', models.IntegerField(help_text='7/7 column Column V')),
                ('current_season_week_two_of_last_four_neos', models.IntegerField(help_text='30/06 column Column V')),
                ('current_season_week_one_of_last_four_neos', models.IntegerField(help_text='23/6 column Column V')),
                ('mix_sales_grp_last_season', models.IntegerField(help_text='GRP 2018 column W')),
                ('y7_left', models.IntegerField(help_text='y7_left Column X')),
                ('adj_capacity', models.IntegerField(help_text='adj capacity Column Y', null=True)),
                ('avg_pick_up', models.FloatField(help_text='Avg pick up Column Z')),
                ('pax_py', models.IntegerField(help_text='Pax PY Column AA')),
                ('pax_CY', models.IntegerField(help_text='PAX CY Column AB')),
                ('plus_or_minus', models.IntegerField(help_text=' +/- Column AC', null=True)),
                ('precl_pax', models.IntegerField(help_text='precl pax Column AD')),
                ('delta_perc_Pax_Res_PY', models.FloatField(help_text='∆% Pax. Res PY Column AE')),
                ('new_capacity', models.IntegerField(help_text='new capacity Column AF')),
                ('tot_pax_cy', models.IntegerField(help_text='tot_pax_cy column AG')),
                ('new_perc_lf', models.IntegerField(help_text='new % LF column AH')),
                ('pax_neos', models.IntegerField(help_text='Pax Neos column AI')),
                ('to_capacity', models.IntegerField(help_text='To Capacity column AI')),
                ('to_pax', models.IntegerField(help_text='To Pax column AI')),
                ('to_perc_lf', models.IntegerField(help_text='To % LF column AI')),
                ('pax_to_perc_forecast', models.IntegerField(help_text='Pax to % forecast column AL', null=True)),
                ('pax_py_residui', models.IntegerField(help_text='Pax PY Residui column AL')),
                ('pax_cy_residui', models.IntegerField(help_text='Pax CY column AL')),
                ('tot_pax_target', models.IntegerField(help_text='Tot Pax Target column AL')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Destination')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Week')),
            ],
        ),
    ]
