# Generated by Django 2.2.3 on 2019-07-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedb',
            name='avg_pick_up',
            field=models.DecimalField(decimal_places=3, help_text='Avg pick up Column Z', max_digits=14),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='delta_perc_Pax_Res_PY',
            field=models.DecimalField(decimal_places=3, help_text='∆% Pax. Res PY Column AE', max_digits=14),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='e_z',
            field=models.IntegerField(help_text='E-Z Column D', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='gar_last_season_consumptive',
            field=models.IntegerField(help_text='Gar Column E', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='pax_last_season_consumptive',
            field=models.IntegerField(help_text='Pax Column F', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='perc_e_z',
            field=models.DecimalField(decimal_places=3, help_text='% E-Z Column H', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='perc_occ',
            field=models.DecimalField(decimal_places=3, help_text='% occ Column L', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='perc_occ_current_season',
            field=models.DecimalField(decimal_places=3, help_text='% occ Column O', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='perc_occ_forecast',
            field=models.DecimalField(decimal_places=3, help_text='% occ Column R', max_digits=14, null=True),
        ),
    ]
