# Generated by Django 2.2.5 on 2019-09-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190731_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedb',
            name='neos_last_season_consumptive',
            field=models.IntegerField(help_text='Neos Column G', null=True),
        ),
    ]
