# Generated by Django 2.2.5 on 2019-09-09 12:56

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190904_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file', models.FileField(upload_to='inputs/%Y/%m/%d/')),
                ('name', models.CharField(db_index=True, help_text='Original File name while importing', max_length=300)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stagedb',
            name='import_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ImportFile'),
        ),
    ]
