# Generated by Django 2.2.5 on 2019-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190909_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedb',
            name='row_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stagedb',
            name='sheet_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
