# Generated by Django 2.2.5 on 2019-09-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190909_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='name',
            field=models.CharField(help_text='Original File name while importing', max_length=300, unique=True),
        ),
    ]
