# Generated by Django 2.2.5 on 2019-09-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190909_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedb',
            name='avg_pick_up',
            field=models.DecimalField(decimal_places=3, help_text='Avg pick up Column Z', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='current_season_week_four_of_last_four',
            field=models.IntegerField(help_text='14/7 column Column T', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='current_season_week_four_of_last_four_neos',
            field=models.IntegerField(help_text='14/7 column Column V', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='current_season_week_one_of_last_four',
            field=models.IntegerField(help_text='23/6 column Column T', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='current_season_week_one_of_last_four_neos',
            field=models.IntegerField(help_text='23/6 column Column V', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='current_season_week_three_of_last_four',
            field=models.IntegerField(help_text='7/7 column Column T', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='current_season_week_three_of_last_four_neos',
            field=models.IntegerField(help_text='7/7 column Column V', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='current_season_week_two_of_last_four',
            field=models.IntegerField(help_text='30/06 column Column T', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='current_season_week_two_of_last_four_neos',
            field=models.IntegerField(help_text='30/06 column Column V', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='delta_gar',
            field=models.IntegerField(help_text=' Delta Gar Column Q', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='delta_pax',
            field=models.IntegerField(help_text='Delta Pax Column Q', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='delta_perc_Pax_Res_PY',
            field=models.DecimalField(decimal_places=3, help_text='∆% Pax. Res PY Column AE', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='gar_current_season',
            field=models.IntegerField(help_text='Gar Column M', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='gar_last_season_on_date',
            field=models.IntegerField(help_text='Gar Column I', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='last_season_week_four_of_last_four',
            field=models.IntegerField(help_text='15/7 column Column S', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='last_season_week_four_of_last_four_neos',
            field=models.IntegerField(help_text='15/7 column Column U', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='last_season_week_one_of_last_four',
            field=models.IntegerField(help_text='24/6 column Column S', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='last_season_week_one_of_last_four_neos',
            field=models.IntegerField(help_text='24/6 column Column U', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='last_season_week_three_of_last_four',
            field=models.IntegerField(help_text='8/7 column Column S', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='last_season_week_three_of_last_four_neos',
            field=models.IntegerField(help_text='8/7 column Column U', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='last_season_week_two_of_last_four',
            field=models.IntegerField(help_text='1/7 column Column S', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='last_season_week_two_of_last_four_neos',
            field=models.IntegerField(help_text='1/7 column Column U', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='mix_sales_grp_last_season',
            field=models.IntegerField(help_text='GRP 2018 column W', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='neos_current_season',
            field=models.IntegerField(help_text='Neos Column P', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='neos_last_season_on_date',
            field=models.IntegerField(help_text='Neos Column K', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='new_capacity',
            field=models.IntegerField(help_text='new capacity Column AF', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='new_perc_lf',
            field=models.IntegerField(help_text='new % LF column AH', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='pax_CY',
            field=models.IntegerField(help_text='PAX CY Column AB', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='pax_current_season',
            field=models.IntegerField(help_text='Pax Column N', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='pax_cy_residui',
            field=models.IntegerField(help_text='Pax CY column AL', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='pax_last_season_on_date',
            field=models.IntegerField(help_text='Pax Column J', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='pax_neos',
            field=models.IntegerField(help_text='Pax Neos column AI', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='pax_py',
            field=models.IntegerField(help_text='Pax PY Column AA', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='pax_py_residui',
            field=models.IntegerField(help_text='Pax PY Residui column AL', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='precl_pax',
            field=models.IntegerField(help_text='precl pax Column AD', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='to_capacity',
            field=models.IntegerField(help_text='To Capacity column AI', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='to_pax',
            field=models.IntegerField(help_text='To Pax column AI', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='to_perc_lf',
            field=models.IntegerField(help_text='To % LF column AI', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='tot_pax_cy',
            field=models.IntegerField(help_text='tot_pax_cy column AG', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='tot_pax_target',
            field=models.IntegerField(help_text='Tot Pax Target column AL', null=True),
        ),
        migrations.AlterField(
            model_name='stagedb',
            name='y7_left',
            field=models.IntegerField(help_text='y7_left Column X', null=True),
        ),
    ]
