# Generated by Django 2.2.5 on 2019-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0007_auto_20190909_1759")]

    operations = [
        migrations.AddField(
            model_name="importfile",
            name="output_file",
            field=models.FileField(null=True, upload_to="outputs/%Y/%m/%d/"),
        )
    ]
