# Generated by Django 2.2.5 on 2019-09-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0008_importfile_output_file")]

    operations = [
        migrations.AddField(
            model_name="stagedb",
            name="curr_est_grp",
            field=models.IntegerField(null=True, verbose_name="estate-4 : GRP"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_est_grp_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="estate-4 : % GRP",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_est_ind",
            field=models.IntegerField(null=True, verbose_name="estate-4 : IND"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_est_ind_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="estate-4 : % IND",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_season_opz",
            field=models.IntegerField(
                help_text="Port-2 : Opz", null=True, verbose_name="Port-2 : Opz"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_season_opz_grp",
            field=models.IntegerField(
                help_text="Port-2 : Opz. GRP",
                null=True,
                verbose_name="Port-2 : Opz. GRP",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_season_opz_ind",
            field=models.IntegerField(
                help_text="Port-2 : Opz. IND",
                null=True,
                verbose_name="Port-2 : Opz. IND",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_season_perc_occ",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Port-2 : % Occ",
                max_digits=14,
                null=True,
                verbose_name="Port-2 : % Occ",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_season_resd",
            field=models.IntegerField(
                help_text="Port-2 : Residui", null=True, verbose_name="Port-2 : Residui"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_season_sv",
            field=models.IntegerField(
                help_text="Port-2 : SV", null=True, verbose_name="Port-2 : SV"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_season_tl",
            field=models.IntegerField(
                help_text="Port-2 : TL", null=True, verbose_name="Port-2 : TL"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_year_pax_diff",
            field=models.DecimalField(
                decimal_places=3,
                help_text="2016 : Δ Pax",
                max_digits=14,
                null=True,
                verbose_name="2016 : Δ Pax",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="curr_year_pax_diff_perc",
            field=models.DecimalField(
                decimal_places=3,
                help_text="2016 : Δ% Pax",
                max_digits=14,
                null=True,
                verbose_name="2016 : Δ% Pax",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="delta_gar_perc",
            field=models.DecimalField(
                decimal_places=3,
                help_text="delta : Δ% Gar",
                max_digits=14,
                null=True,
                verbose_name="delta : Δ% Gar",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="delta_pax_perc",
            field=models.DecimalField(
                decimal_places=3,
                help_text="delta : Δ% Pax",
                max_digits=14,
                null=True,
                verbose_name="delta : Δ% Pax",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="dep_date_return_gar",
            field=models.IntegerField(null=True, verbose_name="Port-4 : Gar"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="dep_date_return_neos",
            field=models.IntegerField(null=True, verbose_name="Port-4 : NEOS"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="dep_date_return_occ_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Port-4 : % Occ.",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="dep_date_return_on_sale",
            field=models.IntegerField(null=True, verbose_name="Port-4 : On-Sale"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="dep_date_return_on_sale_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Port-4 : % On-Sale",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="dep_date_return_opz",
            field=models.IntegerField(null=True, verbose_name="Port-4 : Opz"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="dep_date_return_opz_grp",
            field=models.IntegerField(null=True, verbose_name="Port-4 : Opz. GRP"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="dep_date_return_opz_ind",
            field=models.IntegerField(null=True, verbose_name="Port-4 : Opz. IND"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="dep_date_return_pax",
            field=models.IntegerField(null=True, verbose_name="Port-4 : Pax"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="elasticity",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Elasticità :"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="last_est_grp",
            field=models.IntegerField(null=True, verbose_name="estate-3 : GRP"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="last_est_grp_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="estate-3 : % GRP",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="last_est_ind",
            field=models.IntegerField(null=True, verbose_name="estate-3 : IND"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="last_est_ind_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="estate-3 : % IND",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="lb_occ_perc",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="LB\n%occ. :"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="on_sale_curr_season",
            field=models.IntegerField(
                help_text="Port-2 : On-Sale", null=True, verbose_name="Port-2 : On-Sale"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="pax_incr_diff",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Δ Pax Incr. :"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="pax_incr_f_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Pax Incr.\nvs. F[%occ] :",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="perc_occ_consumptive",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Consuntivo : % Occ.",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="pickup_2_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Pick-Up\n2 weeks :",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="pickup_4_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Pick-Up\n4 weeks :",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="price_diff",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Δ prezzo :"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="rotation_gar",
            field=models.IntegerField(null=True, verbose_name="Port-5 : Gar"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="rotation_neos",
            field=models.IntegerField(null=True, verbose_name="Port-5 : NEOS"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="rotation_occ_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Port-5 : % Occ.",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="rotation_on_sale",
            field=models.IntegerField(null=True, verbose_name="Port-5 : On-Sale"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="rotation_on_sale_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Port-5 : % On-Sale",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="rotation_opz",
            field=models.IntegerField(null=True, verbose_name="Port-5 : Opz"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="rotation_opz_grp",
            field=models.IntegerField(null=True, verbose_name="Port-5 : Opz. GRP"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="rotation_opz_ind",
            field=models.IntegerField(null=True, verbose_name="Port-5 : Opz. IND"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="rotation_pax",
            field=models.IntegerField(null=True, verbose_name="Port-5 : Pax"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="seats_incr_f_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Seats Incr.\nvs. F[%occ] :",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="seven_day_return_gar",
            field=models.IntegerField(null=True, verbose_name="Port-3 : Gar"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="seven_day_return_neos",
            field=models.IntegerField(null=True, verbose_name="Port-3 : NEOS"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="seven_day_return_occ_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Port-3 : % Occ.",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="seven_day_return_on_sale",
            field=models.IntegerField(null=True, verbose_name="Port-3 : On-Sale"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="seven_day_return_on_sale_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Port-3 : % On-Sale",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="seven_day_return_opz",
            field=models.IntegerField(null=True, verbose_name="Port-3 : Opz"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="seven_day_return_opz_grp",
            field=models.IntegerField(null=True, verbose_name="Port-3 : Opz. GRP"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="seven_day_return_opz_ind",
            field=models.IntegerField(null=True, verbose_name="Port-3 : Opz. IND"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="seven_day_return_pax",
            field=models.IntegerField(null=True, verbose_name="Port-3 : Pax"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="wt_2_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Weight\n2 weeks :",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="wt_4_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Weight\n4 weeks :",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="adj_capacity",
            field=models.IntegerField(
                help_text="adj capacity Column Y",
                null=True,
                verbose_name="adj.\ncapacity",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="avg_pick_up",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Avg pick up Column Z",
                max_digits=14,
                null=True,
                verbose_name="Avg.\nPick-Up",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_four_of_last_four",
            field=models.IntegerField(
                help_text="14/7 column Column T", null=True, verbose_name="estate-2 : 4"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_four_of_last_four_neos",
            field=models.IntegerField(
                help_text="14/7 column Column V", null=True, verbose_name="neos-2 : 4"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_one_of_last_four",
            field=models.IntegerField(
                help_text="23/6 column Column T", null=True, verbose_name="estate-2 : 1"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_one_of_last_four_neos",
            field=models.IntegerField(
                help_text="23/6 column Column V", null=True, verbose_name="neos-2 : 1"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_three_of_last_four",
            field=models.IntegerField(
                help_text="7/7 column Column T", null=True, verbose_name="estate-2 : 3"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_three_of_last_four_neos",
            field=models.IntegerField(
                help_text="7/7 column Column V", null=True, verbose_name="neos-2 : 3"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_two_of_last_four",
            field=models.IntegerField(
                help_text="30/06 column Column T",
                null=True,
                verbose_name="estate-2 : 2",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_two_of_last_four_neos",
            field=models.IntegerField(
                help_text="30/06 column Column V", null=True, verbose_name="neos-2 : 2"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="delta_gar",
            field=models.IntegerField(
                help_text=" Delta Gar Column Q", null=True, verbose_name="delta : Δ Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="delta_pax",
            field=models.IntegerField(
                help_text="Delta Pax Column Q", null=True, verbose_name="delta : Δ Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="delta_perc_Pax_Res_PY",
            field=models.DecimalField(
                decimal_places=3,
                help_text="∆% Pax. Res PY Column AE",
                max_digits=14,
                null=True,
                verbose_name="Δ% Pax\nRes PY",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="e_z",
            field=models.IntegerField(
                help_text="E-Z Column D", null=True, verbose_name="Consuntivo : E-Z"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="gar_current_season",
            field=models.IntegerField(
                help_text="Gar Column M", null=True, verbose_name="Port-2 : Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="gar_forecast",
            field=models.IntegerField(
                help_text="Gar Column R", null=True, verbose_name="forecast : Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="gar_last_season_consumptive",
            field=models.IntegerField(
                help_text="Gar Column E", null=True, verbose_name="Consuntivo : Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="gar_last_season_on_date",
            field=models.IntegerField(
                help_text="Gar Column I", null=True, verbose_name="Port-1 : Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_four_of_last_four",
            field=models.IntegerField(
                help_text="15/7 column Column S", null=True, verbose_name="estate-1 : 4"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_four_of_last_four_neos",
            field=models.IntegerField(
                help_text="15/7 column Column U", null=True, verbose_name="neos-1 : 4"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_one_of_last_four",
            field=models.IntegerField(
                help_text="24/6 column Column S", null=True, verbose_name="estate-1 : 1"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_one_of_last_four_neos",
            field=models.IntegerField(
                help_text="24/6 column Column U", null=True, verbose_name="neos-1 : 1"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_three_of_last_four",
            field=models.IntegerField(
                help_text="8/7 column Column S", null=True, verbose_name="estate-1 : 3"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_three_of_last_four_neos",
            field=models.IntegerField(
                help_text="8/7 column Column U", null=True, verbose_name="neos-1 : 3"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_two_of_last_four",
            field=models.IntegerField(
                help_text="1/7 column Column S", null=True, verbose_name="estate-1 : 2"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_two_of_last_four_neos",
            field=models.IntegerField(
                help_text="1/7 column Column U", null=True, verbose_name="neos-1 : 2"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="mix_sales_grp_last_season",
            field=models.IntegerField(
                help_text="GRP 2018 column W",
                null=True,
                verbose_name="last-sales : GRP",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="neos_current_season",
            field=models.IntegerField(
                help_text="Neos Column P", null=True, verbose_name="Port-2 : NEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="neos_forecast",
            field=models.IntegerField(
                help_text="Neos Column R", null=True, verbose_name="forecast : NEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="neos_last_season_consumptive",
            field=models.IntegerField(
                help_text="Neos Column G", null=True, verbose_name="Consuntivo : NEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="neos_last_season_on_date",
            field=models.IntegerField(
                help_text="Neos Column K", null=True, verbose_name="Port-1 : NEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="new_capacity",
            field=models.IntegerField(
                help_text="new capacity Column AF",
                null=True,
                verbose_name="new\ncapacity",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="new_perc_lf",
            field=models.IntegerField(
                help_text="new % LF column AH", null=True, verbose_name="New\n%LF"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_CY",
            field=models.IntegerField(
                help_text="PAX CY Column AB", null=True, verbose_name="Pax\nCY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_current_season",
            field=models.IntegerField(
                help_text="Pax Column N", null=True, verbose_name="Port-2 : Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_cy_residui",
            field=models.IntegerField(
                help_text="Pax CY column AL", null=True, verbose_name="Pax CY Residui"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_forecast",
            field=models.IntegerField(
                help_text="Pax Column R", null=True, verbose_name="forecast : Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_last_season_consumptive",
            field=models.IntegerField(
                help_text="Pax Column F", null=True, verbose_name="Consuntivo : Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_last_season_on_date",
            field=models.IntegerField(
                help_text="Pax Column J", null=True, verbose_name="Port-1 : Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_neos",
            field=models.IntegerField(
                help_text="Pax Neos column AI", null=True, verbose_name="Pax\nNEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_py",
            field=models.IntegerField(
                help_text="Pax PY Column AA", null=True, verbose_name="Pax\nPY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_py_residui",
            field=models.IntegerField(
                help_text="Pax PY Residui column AL",
                null=True,
                verbose_name="Pax PY Residui",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_to_perc_forecast",
            field=models.IntegerField(
                help_text="Pax to % forecast column AL",
                null=True,
                verbose_name="Pax to \n%Forecast",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_e_z",
            field=models.DecimalField(
                decimal_places=3,
                help_text="% E-Z Column H",
                max_digits=14,
                null=True,
                verbose_name="Consuntivo : % E-Z",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_occ",
            field=models.DecimalField(
                decimal_places=3,
                help_text="% occ Column L",
                max_digits=14,
                null=True,
                verbose_name="Port-1 : % Occ.",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_occ_current_season",
            field=models.DecimalField(
                decimal_places=3,
                help_text="% occ Column O",
                max_digits=14,
                null=True,
                verbose_name="Port-2 : % Occ.",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_occ_forecast",
            field=models.DecimalField(
                decimal_places=3,
                help_text="% occ Column R",
                max_digits=14,
                null=True,
                verbose_name="forecast : % Occ.",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="plus_or_minus",
            field=models.IntegerField(
                help_text=" +/- Column AC", null=True, verbose_name="+/-"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="precl_pax",
            field=models.IntegerField(
                help_text="precl pax Column AD", null=True, verbose_name="Precl.\nPax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_capacity",
            field=models.IntegerField(
                help_text="To Capacity column AI", null=True, verbose_name="TO capacity"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_pax",
            field=models.IntegerField(
                help_text="To Pax column AI", null=True, verbose_name="TO\npax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_perc_lf",
            field=models.IntegerField(
                help_text="To % LF column AI", null=True, verbose_name="TO\n%LF"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="tot_pax_cy",
            field=models.IntegerField(
                help_text="tot_pax_cy column AG", null=True, verbose_name="Tot.\nPax CY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="tot_pax_target",
            field=models.IntegerField(
                help_text="Tot Pax Target column AL",
                null=True,
                verbose_name="Tot Pax\nTarget",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="y7_left",
            field=models.IntegerField(
                help_text="y7_left Column X", null=True, verbose_name="y7 left"
            ),
        ),
    ]
