# Generated by Django 2.2.5 on 2019-09-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0009_auto_20190913_0920")]

    operations = [
        migrations.AlterField(
            model_name="stagedb",
            name="curr_year_pax_diff",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="budget : Δ Pax",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="curr_year_pax_diff_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="budget : Δ% Pax",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="gar_forecast",
            field=models.IntegerField(
                help_text="Gar Column R", null=True, verbose_name="budget : Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="neos_forecast",
            field=models.IntegerField(
                help_text="Neos Column R", null=True, verbose_name="budget : NEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_forecast",
            field=models.IntegerField(
                help_text="Pax Column R", null=True, verbose_name="budget : Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_occ_forecast",
            field=models.DecimalField(
                decimal_places=3,
                help_text="% occ Column R",
                max_digits=14,
                null=True,
                verbose_name="budget : % Occ.",
            ),
        ),
    ]
