# Generated by Django 2.2.5 on 2019-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0010_auto_20190913_1306")]

    operations = [
        migrations.AddField(
            model_name="stagedb",
            name="adj_capacity_plus_mins",
            field=models.IntegerField(null=True, verbose_name="adj +/- capacity"),
        )
    ]
