# Generated by Django 2.2.5 on 2019-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0011_stagedb_adj_capacity_plus_mins")]

    operations = [
        migrations.AlterField(
            model_name="stagedb",
            name="elasticity",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Elasticità"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="lb_occ_perc",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="LB\n%occ."
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_incr_diff",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Δ Pax Incr."
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_incr_f_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Pax Incr.\nvs. F[%occ]",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pickup_2_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Pick-Up\n2 weeks",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pickup_4_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Pick-Up\n4 weeks",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="price_diff",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Δ prezzo"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seats_incr_f_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Seats Incr.\nvs. F[%occ]",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="wt_2_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Weight\n2 weeks",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="wt_4_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Weight\n4 weeks",
            ),
        ),
    ]
