# Generated by Django 2.2.5 on 2019-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0012_auto_20190913_1435")]

    operations = [
        migrations.AddField(
            model_name="stagedb",
            name="diff_pax_vs_forecast",
            field=models.IntegerField(null=True, verbose_name="Δ Pax vs. \nForecast"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="to_capacity_2",
            field=models.IntegerField(null=True, verbose_name="TO capacity-2"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="new_perc_lf",
            field=models.IntegerField(null=True, verbose_name="New\n%LF"),
        ),
    ]
