# Generated by Django 2.2.5 on 2019-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0013_auto_20190913_1606")]

    operations = [
        migrations.AddField(
            model_name="stagedb",
            name="flag_neos",
            field=models.IntegerField(null=True, verbose_name="flag\nNEOS"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="gar_last_season_consumptive_2",
            field=models.IntegerField(null=True, verbose_name="Consuntivo : Gar-2"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="lf_lw_perc",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="%LF\nLW"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="lf_perc",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="%LF\nPrec"
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="mix_sales_grp_curr_season",
            field=models.IntegerField(null=True, verbose_name="curr-sales : GRP"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="mix_sales_grp_curr_season_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="curr-sales : % GRP",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="mix_sales_grp_last_season_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="last-sales : % GRP",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="mix_sales_ind_curr_season",
            field=models.IntegerField(null=True, verbose_name="curr-sales : IND"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="mix_sales_ind_curr_season_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="curr-sales : % IND",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="mix_sales_ind_last_season",
            field=models.IntegerField(null=True, verbose_name="last-sales : IND"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="mix_sales_ind_last_season_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="last-sales : % IND",
            ),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="pax_vs_lw_perc",
            field=models.IntegerField(null=True, verbose_name="Δ Pax vs. LW"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="precl_pax_lw",
            field=models.IntegerField(null=True, verbose_name="Precl.\nPax LW"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="price_pax_vs_forecast",
            field=models.IntegerField(null=True, verbose_name="ε Pax vs.\nForecast"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="tl_last_season_consumptive",
            field=models.IntegerField(null=True, verbose_name="Consuntivo : TL"),
        ),
        migrations.AddField(
            model_name="stagedb",
            name="tl_perc_last_season",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Consuntivo : % TL",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="delta_perc_Pax_Res_PY",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Δ% Pax\nRes PY",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="mix_sales_grp_last_season",
            field=models.IntegerField(null=True, verbose_name="last-sales : GRP"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="neos_last_season_consumptive",
            field=models.IntegerField(null=True, verbose_name="Consuntivo : NEOS"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_last_season_consumptive",
            field=models.IntegerField(null=True, verbose_name="Consuntivo : Pax"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_neos",
            field=models.IntegerField(null=True, verbose_name="Pax\nNEOS"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_e_z",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Consuntivo : % E-Z",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="precl_pax",
            field=models.IntegerField(null=True, verbose_name="Precl.\nPax"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_capacity",
            field=models.IntegerField(null=True, verbose_name="TO capacity"),
        ),
    ]
