# Generated by Django 2.2.5 on 2019-09-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0014_auto_20190914_1912")]

    operations = [
        migrations.AlterField(
            model_name="stagedb",
            name="avg_pick_up",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Avg pick up Column Z",
                max_digits=14,
                null=True,
                verbose_name="Avg. Pick-Up",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="delta_perc_Pax_Res_PY",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Δ% Pax Res PY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="diff_pax_vs_forecast",
            field=models.IntegerField(null=True, verbose_name="Δ Pax vs. Forecast"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="flag_neos",
            field=models.IntegerField(null=True, verbose_name="flag NEOS"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="lb_occ_perc",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="LB %occ."
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="lf_lw_perc",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="%LF LW"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="lf_perc",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="%LF Prec"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="new_capacity",
            field=models.IntegerField(
                help_text="new capacity Column AF",
                null=True,
                verbose_name="new capacity",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="new_perc_lf",
            field=models.IntegerField(null=True, verbose_name="New %LF"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_CY",
            field=models.IntegerField(
                help_text="PAX CY Column AB", null=True, verbose_name="Pax CY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_incr_f_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Pax Incr. vs. F[%occ]",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_neos",
            field=models.IntegerField(null=True, verbose_name="Pax NEOS"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_py",
            field=models.IntegerField(
                help_text="Pax PY Column AA", null=True, verbose_name="Pax PY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_to_perc_forecast",
            field=models.IntegerField(null=True, verbose_name="Pax to %Forecast"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pickup_2_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Pick-Up 2 weeks",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pickup_4_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Pick-Up 4 weeks",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="precl_pax",
            field=models.IntegerField(null=True, verbose_name="Precl. Pax"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="precl_pax_lw",
            field=models.IntegerField(null=True, verbose_name="Precl. Pax LW"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="price_pax_vs_forecast",
            field=models.IntegerField(null=True, verbose_name="ε Pax vs. Forecast"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seats_incr_f_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Seats Incr. vs. F[%occ]",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_pax",
            field=models.IntegerField(
                help_text="To Pax column AI", null=True, verbose_name="TO pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_perc_lf",
            field=models.IntegerField(null=True, verbose_name="TO %LF"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="tot_pax_cy",
            field=models.IntegerField(
                help_text="tot_pax_cy column AG", null=True, verbose_name="Tot. Pax CY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="tot_pax_target",
            field=models.IntegerField(
                help_text="Tot Pax Target column AL",
                null=True,
                verbose_name="Tot Pax Target",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="wt_2_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Weight 2 weeks",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="wt_4_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="%Weight 4 weeks",
            ),
        ),
    ]
