# Generated by Django 2.2.5 on 2019-09-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0015_auto_20190914_2101")]

    operations = [
        migrations.AlterField(
            model_name="stagedb",
            name="new_perc_lf",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="New %LF"
            ),
        )
    ]
