# Generated by Django 2.2.5 on 2019-09-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0016_auto_20190914_2120")]

    operations = [
        migrations.AlterField(
            model_name="stagedb",
            name="avg_pick_up",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Avg. Pick-Up"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="diff_pax_vs_forecast",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Δ Pax vs. Forecast",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="price_pax_vs_forecast",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="ε Pax vs. Forecast",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_perc_lf",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="TO %LF"
            ),
        ),
    ]
