# Generated by Django 2.2.5 on 2019-09-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0017_auto_20190914_2127")]

    operations = [
        migrations.RemoveField(model_name="stagedb", name="curr_est_grp"),
        migrations.RemoveField(model_name="stagedb", name="curr_est_grp_perc"),
        migrations.RemoveField(model_name="stagedb", name="curr_est_ind"),
        migrations.RemoveField(model_name="stagedb", name="curr_est_ind_perc"),
        migrations.RemoveField(model_name="stagedb", name="last_est_grp"),
        migrations.RemoveField(model_name="stagedb", name="last_est_grp_perc"),
        migrations.RemoveField(model_name="stagedb", name="last_est_ind"),
        migrations.RemoveField(model_name="stagedb", name="last_est_ind_perc"),
    ]
