# Generated by Django 2.2.5 on 2019-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0018_auto_20190915_1427")]

    operations = [
        migrations.AlterField(
            model_name="stagedb",
            name="new_capacity",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="new capacity"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_CY",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Pax CY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_cy_residui",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Pax CY Residui",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_neos",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Pax NEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_py",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Pax PY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_py_residui",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Pax PY Residui column AL",
                max_digits=14,
                null=True,
                verbose_name="Pax PY Residui",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_to_perc_forecast",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Pax to %Forecast",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_vs_lw_perc",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Δ Pax vs. LW"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="precl_pax",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Precl. Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="precl_pax_lw",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Precl. Pax LW"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_capacity",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="TO capacity"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_capacity_2",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="TO capacity-2"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_pax",
            field=models.DecimalField(
                decimal_places=3,
                help_text="To Pax column AI",
                max_digits=14,
                null=True,
                verbose_name="TO pax",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="tot_pax_cy",
            field=models.DecimalField(
                decimal_places=3, max_digits=14, null=True, verbose_name="Tot. Pax CY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="tot_pax_target",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=14,
                null=True,
                verbose_name="Tot Pax Target",
            ),
        ),
    ]
