# Generated by Django 2.2.5 on 2019-09-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0019_auto_20190918_1414")]

    operations = [
        migrations.AlterField(
            model_name="stagedb",
            name="adj_capacity",
            field=models.IntegerField(
                default=0,
                help_text="adj capacity Column Y",
                verbose_name="adj.\ncapacity",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="adj_capacity_plus_mins",
            field=models.IntegerField(default=0, verbose_name="adj +/- capacity"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="avg_pick_up",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Avg. Pick-Up"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="curr_season_opz",
            field=models.IntegerField(
                default=0, help_text="Port-2 : Opz", verbose_name="Port-2 : Opz"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="curr_season_opz_grp",
            field=models.IntegerField(
                default=0,
                help_text="Port-2 : Opz. GRP",
                verbose_name="Port-2 : Opz. GRP",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="curr_season_opz_ind",
            field=models.IntegerField(
                default=0,
                help_text="Port-2 : Opz. IND",
                verbose_name="Port-2 : Opz. IND",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="curr_season_perc_occ",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Port-2 : % Occ",
                max_digits=14,
                verbose_name="Port-2 : % Occ",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="curr_season_resd",
            field=models.IntegerField(
                default=0, help_text="Port-2 : Residui", verbose_name="Port-2 : Residui"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="curr_season_sv",
            field=models.IntegerField(
                default=0, help_text="Port-2 : SV", verbose_name="Port-2 : SV"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="curr_season_tl",
            field=models.IntegerField(
                default=0, help_text="Port-2 : TL", verbose_name="Port-2 : TL"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="curr_year_pax_diff",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="budget : Δ Pax",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="curr_year_pax_diff_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="budget : Δ% Pax",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_four_of_last_four",
            field=models.IntegerField(
                default=0, help_text="14/7 column Column T", verbose_name="estate-2 : 4"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_four_of_last_four_neos",
            field=models.IntegerField(
                default=0, help_text="14/7 column Column V", verbose_name="neos-2 : 4"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_one_of_last_four",
            field=models.IntegerField(
                default=0, help_text="23/6 column Column T", verbose_name="estate-2 : 1"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_one_of_last_four_neos",
            field=models.IntegerField(
                default=0, help_text="23/6 column Column V", verbose_name="neos-2 : 1"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_three_of_last_four",
            field=models.IntegerField(
                default=0, help_text="7/7 column Column T", verbose_name="estate-2 : 3"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_three_of_last_four_neos",
            field=models.IntegerField(
                default=0, help_text="7/7 column Column V", verbose_name="neos-2 : 3"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_two_of_last_four",
            field=models.IntegerField(
                default=0,
                help_text="30/06 column Column T",
                verbose_name="estate-2 : 2",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="current_season_week_two_of_last_four_neos",
            field=models.IntegerField(
                default=0, help_text="30/06 column Column V", verbose_name="neos-2 : 2"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="delta_gar",
            field=models.IntegerField(
                default=0, help_text=" Delta Gar Column Q", verbose_name="delta : Δ Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="delta_gar_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="delta : Δ% Gar",
                max_digits=14,
                verbose_name="delta : Δ% Gar",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="delta_pax",
            field=models.IntegerField(
                default=0, help_text="Delta Pax Column Q", verbose_name="delta : Δ Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="delta_pax_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="delta : Δ% Pax",
                max_digits=14,
                verbose_name="delta : Δ% Pax",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="delta_perc_Pax_Res_PY",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Δ% Pax Res PY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="dep_date_return_gar",
            field=models.IntegerField(default=0, verbose_name="Port-4 : Gar"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="dep_date_return_neos",
            field=models.IntegerField(default=0, verbose_name="Port-4 : NEOS"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="dep_date_return_occ_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Port-4 : % Occ.",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="dep_date_return_on_sale",
            field=models.IntegerField(default=0, verbose_name="Port-4 : On-Sale"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="dep_date_return_on_sale_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Port-4 : % On-Sale",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="dep_date_return_opz",
            field=models.IntegerField(default=0, verbose_name="Port-4 : Opz"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="dep_date_return_opz_grp",
            field=models.IntegerField(default=0, verbose_name="Port-4 : Opz. GRP"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="dep_date_return_opz_ind",
            field=models.IntegerField(default=0, verbose_name="Port-4 : Opz. IND"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="dep_date_return_pax",
            field=models.IntegerField(default=0, verbose_name="Port-4 : Pax"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="diff_pax_vs_forecast",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Δ Pax vs. Forecast",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="e_z",
            field=models.IntegerField(
                default=0, help_text="E-Z Column D", verbose_name="Consuntivo : E-Z"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="elasticity",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Elasticità"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="flag_neos",
            field=models.IntegerField(default=0, verbose_name="flag NEOS"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="gar_current_season",
            field=models.IntegerField(
                default=0, help_text="Gar Column M", verbose_name="Port-2 : Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="gar_forecast",
            field=models.IntegerField(
                default=0, help_text="Gar Column R", verbose_name="budget : Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="gar_last_season_consumptive",
            field=models.IntegerField(
                default=0, help_text="Gar Column E", verbose_name="Consuntivo : Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="gar_last_season_consumptive_2",
            field=models.IntegerField(default=0, verbose_name="Consuntivo : Gar-2"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="gar_last_season_on_date",
            field=models.IntegerField(
                default=0, help_text="Gar Column I", verbose_name="Port-1 : Gar"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_four_of_last_four",
            field=models.IntegerField(
                default=0, help_text="15/7 column Column S", verbose_name="estate-1 : 4"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_four_of_last_four_neos",
            field=models.IntegerField(
                default=0, help_text="15/7 column Column U", verbose_name="neos-1 : 4"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_one_of_last_four",
            field=models.IntegerField(
                default=0, help_text="24/6 column Column S", verbose_name="estate-1 : 1"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_one_of_last_four_neos",
            field=models.IntegerField(
                default=0, help_text="24/6 column Column U", verbose_name="neos-1 : 1"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_three_of_last_four",
            field=models.IntegerField(
                default=0, help_text="8/7 column Column S", verbose_name="estate-1 : 3"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_three_of_last_four_neos",
            field=models.IntegerField(
                default=0, help_text="8/7 column Column U", verbose_name="neos-1 : 3"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_two_of_last_four",
            field=models.IntegerField(
                default=0, help_text="1/7 column Column S", verbose_name="estate-1 : 2"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="last_season_week_two_of_last_four_neos",
            field=models.IntegerField(
                default=0, help_text="1/7 column Column U", verbose_name="neos-1 : 2"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="lb_occ_perc",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="LB %occ."
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="lf_lw_perc",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="%LF LW"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="lf_perc",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="%LF Prec"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="mix_sales_grp_curr_season",
            field=models.IntegerField(default=0, verbose_name="curr-sales : GRP"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="mix_sales_grp_curr_season_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="curr-sales : % GRP",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="mix_sales_grp_last_season",
            field=models.IntegerField(default=0, verbose_name="last-sales : GRP"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="mix_sales_grp_last_season_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="last-sales : % GRP",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="mix_sales_ind_curr_season",
            field=models.IntegerField(default=0, verbose_name="curr-sales : IND"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="mix_sales_ind_curr_season_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="curr-sales : % IND",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="mix_sales_ind_last_season",
            field=models.IntegerField(default=0, verbose_name="last-sales : IND"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="mix_sales_ind_last_season_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="last-sales : % IND",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="neos_current_season",
            field=models.IntegerField(
                default=0, help_text="Neos Column P", verbose_name="Port-2 : NEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="neos_forecast",
            field=models.IntegerField(
                default=0, help_text="Neos Column R", verbose_name="budget : NEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="neos_last_season_consumptive",
            field=models.IntegerField(default=0, verbose_name="Consuntivo : NEOS"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="neos_last_season_on_date",
            field=models.IntegerField(
                default=0, help_text="Neos Column K", verbose_name="Port-1 : NEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="new_capacity",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="new capacity"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="new_perc_lf",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="New %LF"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="on_sale_curr_season",
            field=models.IntegerField(
                default=0, help_text="Port-2 : On-Sale", verbose_name="Port-2 : On-Sale"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_CY",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Pax CY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_current_season",
            field=models.IntegerField(
                default=0, help_text="Pax Column N", verbose_name="Port-2 : Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_cy_residui",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Pax CY Residui",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_forecast",
            field=models.IntegerField(
                default=0, help_text="Pax Column R", verbose_name="budget : Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_incr_diff",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Δ Pax Incr."
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_incr_f_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Pax Incr. vs. F[%occ]",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_last_season_consumptive",
            field=models.IntegerField(default=0, verbose_name="Consuntivo : Pax"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_last_season_on_date",
            field=models.IntegerField(
                default=0, help_text="Pax Column J", verbose_name="Port-1 : Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_neos",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Pax NEOS"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_py",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Pax PY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_py_residui",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Pax PY Residui column AL",
                max_digits=14,
                verbose_name="Pax PY Residui",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_to_perc_forecast",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Pax to %Forecast",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pax_vs_lw_perc",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Δ Pax vs. LW"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_e_z",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Consuntivo : % E-Z",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_occ",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="% occ Column L",
                max_digits=14,
                verbose_name="Port-1 : % Occ.",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_occ_consumptive",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Consuntivo : % Occ.",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_occ_current_season",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="% occ Column O",
                max_digits=14,
                verbose_name="Port-2 : % Occ.",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="perc_occ_forecast",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="% occ Column R",
                max_digits=14,
                verbose_name="budget : % Occ.",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pickup_2_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="%Pick-Up 2 weeks",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="pickup_4_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="%Pick-Up 4 weeks",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="plus_or_minus",
            field=models.IntegerField(
                default=0, help_text=" +/- Column AC", verbose_name="+/-"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="precl_pax",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Precl. Pax"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="precl_pax_lw",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Precl. Pax LW"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="price_diff",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Δ prezzo"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="price_pax_vs_forecast",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="ε Pax vs. Forecast",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="rotation_gar",
            field=models.IntegerField(default=0, verbose_name="Port-5 : Gar"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="rotation_neos",
            field=models.IntegerField(default=0, verbose_name="Port-5 : NEOS"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="rotation_occ_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Port-5 : % Occ.",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="rotation_on_sale",
            field=models.IntegerField(default=0, verbose_name="Port-5 : On-Sale"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="rotation_on_sale_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Port-5 : % On-Sale",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="rotation_opz",
            field=models.IntegerField(default=0, verbose_name="Port-5 : Opz"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="rotation_opz_grp",
            field=models.IntegerField(default=0, verbose_name="Port-5 : Opz. GRP"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="rotation_opz_ind",
            field=models.IntegerField(default=0, verbose_name="Port-5 : Opz. IND"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="rotation_pax",
            field=models.IntegerField(default=0, verbose_name="Port-5 : Pax"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seats_incr_f_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Seats Incr. vs. F[%occ]",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seven_day_return_gar",
            field=models.IntegerField(default=0, verbose_name="Port-3 : Gar"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seven_day_return_neos",
            field=models.IntegerField(default=0, verbose_name="Port-3 : NEOS"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seven_day_return_occ_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Port-3 : % Occ.",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seven_day_return_on_sale",
            field=models.IntegerField(default=0, verbose_name="Port-3 : On-Sale"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seven_day_return_on_sale_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Port-3 : % On-Sale",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seven_day_return_opz",
            field=models.IntegerField(default=0, verbose_name="Port-3 : Opz"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seven_day_return_opz_grp",
            field=models.IntegerField(default=0, verbose_name="Port-3 : Opz. GRP"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seven_day_return_opz_ind",
            field=models.IntegerField(default=0, verbose_name="Port-3 : Opz. IND"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="seven_day_return_pax",
            field=models.IntegerField(default=0, verbose_name="Port-3 : Pax"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="tl_last_season_consumptive",
            field=models.IntegerField(default=0, verbose_name="Consuntivo : TL"),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="tl_perc_last_season",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Consuntivo : % TL",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_capacity",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="TO capacity"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_capacity_2",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="TO capacity-2"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_pax",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="To Pax column AI",
                max_digits=14,
                verbose_name="TO pax",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="to_perc_lf",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="TO %LF"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="tot_pax_cy",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=14, verbose_name="Tot. Pax CY"
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="tot_pax_target",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="Tot Pax Target",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="wt_2_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="%Weight 2 weeks",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="wt_4_weeks_perc",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                verbose_name="%Weight 4 weeks",
            ),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="y7_left",
            field=models.IntegerField(
                default=0, help_text="y7_left Column X", verbose_name="y7 left"
            ),
        ),
    ]
