# Generated by Django 2.2.5 on 2019-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0020_auto_20190919_1152")]

    operations = [
        migrations.AlterModelOptions(
            name="stagedb", options={"ordering": ["sheet_name", "row_number"]}
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="row_number",
            field=models.PositiveIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="stagedb",
            name="sheet_name",
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
