# Generated by Django 3.0.2 on 2020-01-09 14:14

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190922_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=100, verbose_name='cod_nazione_destinazione')),
                ('name', models.CharField(max_length=300, verbose_name='Nome Paese')),
            ],
            options={
                'verbose_name': 'LookupNazioni',
            },
        ),
        migrations.CreateModel(
            name='ProdOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id_prod', models.CharField(max_length=300, verbose_name='id_prod')),
                ('catalog_id', models.CharField(max_length=300, verbose_name='catalog_id')),
                ('catalog_id22', models.CharField(max_length=300, verbose_name='catalog_id22')),
                ('commission_percent', models.CharField(max_length=300, verbose_name='commission_percent')),
                ('departure_date', models.DateTimeField(verbose_name='departure_date')),
                ('departure_flight_airport2', models.CharField(max_length=300, verbose_name='departure_flight_airport2')),
                ('departure_flight_available_seats', models.CharField(max_length=300, verbose_name='departure_flight_available_seats')),
                ('departure_flight_code', models.CharField(max_length=300, verbose_name='departure_flight_code')),
                ('departure_flight_company', models.CharField(max_length=300, verbose_name='departure_flight_company')),
                ('hotel_category', models.CharField(max_length=300, verbose_name='hotel_category')),
                ('hotel_checking_date', models.DateTimeField(verbose_name='hotel_checking_date')),
                ('hotel_checkout_date', models.DateTimeField(verbose_name='hotel_checkout_date')),
                ('hotel_code', models.CharField(max_length=300, verbose_name='hotel_code')),
                ('hotel_name', models.CharField(max_length=300, verbose_name='hotel_name')),
                ('offer_type', models.CharField(max_length=300, verbose_name='offer_type')),
                ('return_date', models.DateTimeField(verbose_name='return_date')),
                ('return_flight_airport', models.CharField(max_length=300, verbose_name='return_flight_airport')),
                ('return_flight_available_seats', models.IntegerField(verbose_name='return_flight_available_seats')),
                ('return_flight_code', models.CharField(max_length=300, verbose_name='return_flight_code')),
                ('return_flight_company', models.CharField(max_length=300, verbose_name='return_flight_company')),
                ('room_code', models.CharField(max_length=300, verbose_name='room_code')),
                ('total_price', models.CharField(max_length=300, verbose_name='total_price')),
                ('tot_adult', models.CharField(max_length=300, verbose_name='tot_adult')),
                ('tot_children', models.CharField(max_length=300, verbose_name='tot_children')),
                ('tot_infants', models.CharField(max_length=300, verbose_name='tot_infants')),
                ('oftype', models.CharField(max_length=300, verbose_name='type')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=100, verbose_name='Cod zona dest')),
                ('name', models.CharField(max_length=300, verbose_name='Nome Zona')),
            ],
            options={
                'verbose_name': 'Zona',
            },
        ),
        migrations.CreateModel(
            name='SalesUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code_catalog', models.CharField(max_length=300, verbose_name='codice_catalogo')),
                ('cod_IATA_aer_arr', models.CharField(max_length=300, verbose_name='cod_IATA_aer_arr')),
                ('cod_IATA_aer_part', models.CharField(max_length=300, verbose_name='cod_IATA_aer_part')),
                ('cod_room', models.CharField(max_length=300, verbose_name='cod_room')),
                ('departure_date', models.DateTimeField(blank=True, null=True, verbose_name='data_partenza')),
                ('booking_date', models.DateTimeField(max_length=300, verbose_name='data_prenotazione')),
                ('product_description', models.CharField(max_length=300, verbose_name='descr_prodotto')),
                ('stay_duration', models.DurationField(verbose_name='durata_soggiorno')),
                ('id_prod', models.CharField(max_length=300, verbose_name='id_prod')),
                ('id_flight', models.CharField(max_length=300, verbose_name='id_volo_and')),
                ('meal_plan', models.CharField(max_length=300, verbose_name='mealplan')),
                ('n_adults', models.IntegerField(default=0, verbose_name='n_adulti')),
                ('n_children', models.IntegerField(default=0, verbose_name='n_bambini')),
                ('n_infant', models.IntegerField(default=0, verbose_name='n_infant')),
                ('n_booking', models.CharField(max_length=300, verbose_name='n_prenotazione')),
                ('total_booking', models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='totale_prenotazione')),
                ('reservation_status', models.CharField(max_length=300, verbose_name='stato_prenotazione')),
                ('traveler_type', models.CharField(max_length=300, verbose_name='tipo_viaggiatore')),
                ('dest_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='nazione_destinazione')),
                ('dest_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Zone', verbose_name='Zona di Destinazione')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
