# Generated by Django 3.0.2 on 2020-01-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_country_prodoffer_salesupdate_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodoffer',
            old_name='departure_flight_airport2',
            new_name='departure_flight_airport',
        ),
        migrations.RenameField(
            model_name='prodoffer',
            old_name='id_prod',
            new_name='prod_id',
        ),
    ]
