# Generated by Django 3.0.2 on 2020-01-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200112_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodoffer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salesupdate',
            options={},
        ),
    ]
