# Generated by Django 3.0.4 on 2020-03-12 15:32

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import django_extensions.db.fields
import server.apps.travels.models
import social_django.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('alias', models.CharField(db_index=True, max_length=36, unique=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItineraryStepType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('product_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('template_id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('reservation_date_from', models.DateField(blank=True, null=True)),
                ('reservation_date_to', models.DateField(blank=True, null=True)),
                ('departure_date_from', models.DateField(blank=True, null=True)),
                ('departure_date_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItineraryStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('day_from', models.CharField(max_length=50)),
                ('day_to', models.CharField(max_length=50)),
                ('assignation_type', django_enumfield.db.fields.EnumField(default=1, enum=server.apps.travels.models.AssignationType)),
                ('assignation_precedence', models.IntegerField(blank=True, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.Itinerary')),
                ('step_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travels.ItineraryStepType')),
            ],
            options={
                'unique_together': {('itinerary', 'order')},
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.TravelTemplate'),
        ),
        migrations.CreateModel(
            name='ItineraryStepOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('data', social_django.fields.JSONField(blank=True, default=dict, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.ItineraryStep')),
            ],
            options={
                'unique_together': {('name', 'step')},
            },
        ),
        migrations.CreateModel(
            name='ItinerarySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('departure_day_offset', models.IntegerField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('data', social_django.fields.JSONField(blank=True, default=dict, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.Itinerary')),
            ],
            options={
                'unique_together': {('itinerary', 'departure_day_offset', 'valid_from')},
            },
        ),
    ]
