# Generated by Django 3.0.4 on 2020-03-12 16:26
from datetime import datetime

from django.db import migrations


def load_itinerary_step_types(apps, schema_editor):
    ItineraryStepType = apps.get_model("travels", "ItineraryStepType")
    ItineraryStepType(id=0, created=datetime.utcnow(), type="travel").save()
    ItineraryStepType(id=1, created=datetime.utcnow(), type="accommodation").save()


def delete_itinerary_step_types(apps, schema_editor):
    ItineraryStepType = apps.get_model("travels", "ItineraryStepType")
    ItineraryStepType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_itinerary_step_types, delete_itinerary_step_types),
    ]
