# Generated by Django 3.0.4 on 2020-03-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_travelinstance_travelreservation_travelreservationroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelreservation',
            name='product_id',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
