# Generated by Django 3.0.4 on 2020-03-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2business', '0003_auto_20200310_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyairport',
            name='location',
        ),
        migrations.RemoveField(
            model_name='companydestination',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companydestination',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='companyhotel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='companyroomtype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='companyroomtype',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyAirport',
        ),
        migrations.DeleteModel(
            name='CompanyDestination',
        ),
        migrations.DeleteModel(
            name='CompanyHotel',
        ),
        migrations.DeleteModel(
            name='CompanyRoomType',
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
        migrations.DeleteModel(
            name='RoomCategory',
        ),
    ]
