# Generated by Django 3.0.2 on 2020-01-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationservicetype',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
