# Generated by Django 3.0.2 on 2020-01-30 05:59

from django.db import models, migrations
from datetime import datetime


def load_quotation_service_types(apps, schema_editor):
    QuotationServiceType = apps.get_model("orders", "QuotationServiceType")
    QuotationServiceType(id=0, created=datetime.utcnow(), name="Base Price", code="base_price").save()
    QuotationServiceType(id=2, created=datetime.utcnow(), name="Ancillary Service", code="ancillary_service").save()
    QuotationServiceType(id=3, created=datetime.utcnow(), name="Coupon", code="coupon").save()


def delete_quotation_service_types(apps, schema_editor):
    QuotationServiceType = apps.get_model("orders", "QuotationServiceType")
    QuotationServiceType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_quotationservicetype_code'),
    ]

    operations = [
        migrations.RunPython(load_quotation_service_types, delete_quotation_service_types),
    ]
