# Generated by Django 3.0.2 on 2020-01-30 17:14

from django.db import migrations, models
import django_enumfield.db.fields
import server.apps.orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200130_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationservice',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='quotationservice',
            name='unitary_price',
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='price_type',
            field=django_enumfield.db.fields.EnumField(default=1, enum=server.apps.orders.models.PriceType),
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='priority',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
