# Generated by Django 3.0.3 on 2020-02-13 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_quotation_availability_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='allotment_id',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='availability_key',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='occupancy_code',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='optioned',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='passengers',
        ),
        migrations.RemoveField(
            model_name='quotationservice',
            name='quotation',
        ),
        migrations.AddField(
            model_name='passenger',
            name='passenger_index',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuotationRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('room_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('allotment_id', models.CharField(db_index=True, max_length=200)),
                ('availability_key', models.CharField(db_index=True, max_length=600)),
                ('optioned', models.BooleanField(db_index=True)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occupancy_code', models.CharField(db_index=True, max_length=50)),
                ('tot_adults', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('passengers', models.ManyToManyField(to='orders.Passenger')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Quotation')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quotationservice',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.QuotationRoom'),
            preserve_default=False,
        ),
    ]
