# Generated by Django 3.0.3 on 2020-02-17 18:53

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import django_extensions.db.fields
import server.apps.orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200213_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationservice',
            name='selection_type',
            field=django_enumfield.db.fields.EnumField(db_index=True, default=1, enum=server.apps.orders.models.SelectionType),
        ),
        migrations.CreateModel(
            name='QuotationAdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('price_type', django_enumfield.db.fields.EnumField(default=1, enum=server.apps.orders.models.PriceType)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('priority', models.IntegerField()),
                ('quantity_type', django_enumfield.db.fields.EnumField(default=1, enum=server.apps.orders.models.QuantityType)),
                ('service_id', models.CharField(max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.QuotationRoom')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
