# Generated by Django 3.0.3 on 2020-02-18 21:22

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import server.apps.orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200217_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='quotationroom',
            name='passengers',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_state',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='quotation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.Quotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.QuotationRoom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=django_enumfield.db.fields.EnumField(enum=server.apps.orders.models.Gender, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=django_enumfield.db.fields.EnumField(enum=server.apps.orders.models.Gender, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='passenger',
            unique_together={('room', 'passenger_index')},
        ),
    ]
