# Generated by Django 3.0.3 on 2020-02-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200220_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='deposit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
