# Generated by Django 3.0.3 on 2020-03-05 16:10

from django.db import migrations, models
import django_enumfield.db.fields
import django_extensions.db.fields
import django_extensions.db.fields.json
import server.apps.orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_quotation_deposit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('log_type', django_enumfield.db.fields.EnumField(db_index=True, enum=server.apps.orders.models.PaymentLogType)),
                ('quotation_id', models.CharField(db_index=True, max_length=200)),
                ('user_session_id', models.CharField(db_index=True, max_length=200)),
                ('payment_session_id', models.CharField(db_index=True, max_length=200)),
                ('operation_name', models.CharField(db_index=True, max_length=50)),
                ('data', django_extensions.db.fields.json.JSONField(default=dict, null=True)),
                ('error', django_extensions.db.fields.json.JSONField(default=dict, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='paymentattempt',
            name='payment_request_id',
        ),
        migrations.RemoveField(
            model_name='paymentattempt',
            name='raw_transaction_request',
        ),
        migrations.RemoveField(
            model_name='paymentattempt',
            name='raw_transaction_response',
        ),
        migrations.RemoveField(
            model_name='paymentattempt',
            name='raw_verification_request',
        ),
        migrations.RemoveField(
            model_name='paymentattempt',
            name='raw_verification_response',
        ),
        migrations.RemoveField(
            model_name='paymentattempt',
            name='transaction_time',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_session_id',
            field=models.CharField(db_index=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payment_session_id',
            field=models.CharField(db_index=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='transaction_end_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='transaction_initialization_input',
            field=django_extensions.db.fields.json.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='transaction_initialization_output',
            field=django_extensions.db.fields.json.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='transaction_start_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='transaction_verification_input',
            field=django_extensions.db.fields.json.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='transaction_verification_output',
            field=django_extensions.db.fields.json.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='status',
            field=django_enumfield.db.fields.EnumField(db_index=True, default=1, enum=server.apps.orders.models.PaymentStatus),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
    ]
