# Generated by Django 3.0.3 on 2020-03-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_paymentattempt_payment_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_request_id',
        ),
    ]
