# Generated by Django 3.0.4 on 2020-03-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200308_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='linked_reservation_id',
        ),
        migrations.AddField(
            model_name='quotation',
            name='product_version',
            field=models.CharField(db_index=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(db_index=True, default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
