# Generated by Django 3.0.4 on 2020-03-11 20:08

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import django_extensions.db.fields
import server.apps.orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200311_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_type', django_enumfield.db.fields.EnumField(default=1, enum=server.apps.orders.models.PriceType)),
                ('reservation_date_from', models.DateField(blank=True, null=True)),
                ('reservation_date_to', models.DateField(blank=True, null=True)),
                ('departure_date_from', models.DateField(blank=True, null=True)),
                ('departure_date_to', models.DateField(blank=True, null=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PromoCode')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiscountTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_type', django_enumfield.db.fields.EnumField(default=1, enum=server.apps.orders.models.PriceType)),
                ('reservation_date_from', models.DateField(blank=True, null=True)),
                ('reservation_date_to', models.DateField(blank=True, null=True)),
                ('departure_date_from', models.DateField(blank=True, null=True)),
                ('departure_date_to', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=265, null=True)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Quotation')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
