# Generated by Django 3.0.4 on 2020-03-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_discountticket_promocode_promorule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='product_version',
        ),
    ]
