# Generated by Django 3.0.4 on 2020-03-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200326_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountticket',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
