# Generated by Django 3.0.4 on 2020-03-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_discountticket_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationroom',
            name='allotment_id',
        ),
        migrations.AddField(
            model_name='quotationroom',
            name='allotments_id',
            field=models.CharField(db_index=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationroom',
            name='master_allotment_id',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationroom',
            name='tot_allotments',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
