# Generated by Django 3.0.4 on 2020-03-28 11:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200327_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationroom',
            name='allotments_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
