# Generated by Django 3.0.4 on 2020-03-30 12:33

from django.db import migrations, models
import django_enumfield.db.fields
import server.apps.orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200330_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='min_age',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='tax_code',
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=django_enumfield.db.fields.EnumField(enum=server.apps.orders.models.Gender, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='surname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
