# Generated by Django 3.0.5 on 2020-04-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200330_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
